name: Keep Render Alive
on:
  schedule:
    - cron: "*/14 * * * *"   # every 14 minutes (UTC)
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          curl --silent --fail --max-time 10 https://coverlettermaker.onrender.com//health || true